[package]
name = "hydrant-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
anyhow = "1.0.100"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

pallas = "0.33"
hex = "0.4.3"

hydrant = { path = ".." }
